service:
  name: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/sendEmailIAM.yml):sendEmailIAM}

functions:
  sendEmail:
    handler: src/handlers/sendEmail.handler
